# Generated by prefetch-external-dependencies.sh.
# Wazuh DEPS_VERSION 54. Do not edit by hand.
{

  "audit-userspace" = {
    name = "audit-userspace";
    sha256 = "sha256-6Coy5e35OwVRYOFLyX9B3q05KHklhR3ICnY44tTTBDQ=";
  };

  "benchmark" = {
    name = "benchmark";
    sha256 = "sha256-lMV6oMsr142+nnfTMsvGRNrw/s3JoJYyBIvm4J+c7Ws=";
  };

  "bzip2" = {
    name = "bzip2";
    sha256 = "sha256-J2iO4DFqZLOeURssIkBwytl8OUpfcR+dBV/BgJ2JW80=";
  };

  "cJSON" = {
    name = "cJSON";
    sha256 = "sha256-2oCfcLfQOsUprmIj1DkL+ibNKfjDLI6LO2Me+hZniS0=";
  };

  "cpp-httplib" = {
    name = "cpp-httplib";
    sha256 = "sha256-ZRdXMmNhFoa5IZunlsNfVKMG6yfcPHLhgH8qCjTKweg=";
  };

  "curl" = {
    name = "curl";
    sha256 = "sha256-MM9xQuQoJxjOsjfhe1y/da/NfJ84gKA5xe/qYtsJRwk=";
  };

  "dbus" = {
    name = "dbus";
    sha256 = "sha256-fGVKyaT2i1DzLWdJIsGP/nQdMoqX15RFdhj8OgekjTo=";
  };

  "googletest" = {
    name = "googletest";
    sha256 = "sha256-jB6KCn8iHCEl6Z5qy3CdorpHJHa00FfFjeUEvr841Bc=";
  };

  "libarchive" = {
    name = "libarchive";
    sha256 = "sha256-VA/0pV3vp1d4osQFZ6gwZIzlNnuK6hIzZodNlrc074A=";
  };

  "libbpf-bootstrap" = {
    name = "libbpf-bootstrap";
    sha256 = "sha256-b3bQXFpDWCBLnfoKNy8lfROP/4QC/cUkSRNdq5mt8zY=";
  };

  "libdb" = {
    name = "libdb";
    sha256 = "sha256-fpxE6Mf9sYb/UhqNCFsb+mNNNC3Md37Oofv5qYq13F4=";
  };

  "libffi" = {
    name = "libffi";
    sha256 = "sha256-DpcfZLrMIglOifA0u6B1tA7MLCwpAO7NeuhYFf1sn2k=";
  };

  "libpcre2" = {
    name = "libpcre2";
    sha256 = "sha256-WoDWVNfRSz25+jpJ179EpJhoO0Z4SojOxRSosZR2e5I=";
  };

  "libplist" = {
    name = "libplist";
    sha256 = "sha256-iCeNS9/BvWo6GlWk89kzaD0nMroJz3p0n+jsjuxAbjw=";
  };

  "libyaml" = {
    name = "libyaml";
    sha256 = "sha256-NdqtYIs3LVzgmfc4wPIb/MA9aSDZL0SDhsWE5mTxN2o=";
  };

  "lua" = {
    name = "lua";
    sha256 = "sha256-Iz6H6HEJC9MMS2kqxzvXFDYcFQURSOTu7IKKHfhDbso=";
  };

  "lzma" = {
    name = "lzma";
    sha256 = "sha256-TODBktQQcrVnmvibtTHvtoXIJnpLfiAFmZFJrBcCgTQ=";
  };

  "msgpack" = {
    name = "msgpack";
    sha256 = "sha256-BtY7zzKJbNCvVIDEARNLGtHBZv2E6+W0hueSEB7oVOI=";
  };

  "nlohmann" = {
    name = "nlohmann";
    sha256 = "sha256-zvsHk209W/3T78Xpu408gH1oEnO9rC6Ds9Z67y0RWMQ=";
  };

  "openssl" = {
    name = "openssl";
    sha256 = "sha256-A4b+Ogv0i64spNF0KlPfmo/LG3NYO6Iuj4p936E3XNk=";
  };

  "pacman" = {
    name = "pacman";
    sha256 = "sha256-Yxq+Bl7JgttWv+wFzzfDOo9on9f0Fkw5J3KEvXoNDjE=";
  };

  "popt" = {
    name = "popt";
    sha256 = "sha256-1ogKBmIsoy3EqjmtXc977y+qgb2TGvvmS6Q0rY/uHao=";
  };

  "procps" = {
    name = "procps";
    sha256 = "sha256-Ih85XinRvb5LrMnbOWAu7guuaFqTVDe+DX/rQuMZLQc=";
  };

  "rocksdb" = {
    name = "rocksdb";
    sha256 = "sha256-7u1go9Tin3MF55+fXOvUJhF0JhIn8bWn0F2lVWVnVDY=";
  };

  "rpm" = {
    name = "rpm";
    sha256 = "sha256-kNhy9U6rzzdzbZCsF6jTEwEtqE5oWxn9Lav0oBKVcpA=";
  };

  "sqlite" = {
    name = "sqlite";
    sha256 = "sha256-qBv/MLtK/9GwakmD/4jvgntKuuoxkbOa/37bKNHd0AM=";
  };

  "zlib" = {
    name = "zlib";
    sha256 = "sha256-tZ04FJ8MKexU0nZmEevFpRoDK/lxfjmprwD7bLhTK4s=";
  };
}
