#!/usr/bin/env bash
#
# Regenerate external_dependencies.nix for a given Wazuh DEPS_VERSION.
#
# Run this on a host that reaches packages.wazuh.com. The agent sandbox cannot
# reach that host, so the hashes cannot be produced there.
#
# Usage:
#   ./prefetch-external-dependencies.sh                 # uses DEPS_VERSION below
#   DEPS_VERSION=54 ./prefetch-external-dependencies.sh
#   DEPS_VERSION=54 EXTRA_DEPS="flatbuffers jemalloc" ./prefetch-external-dependencies.sh
#
# The script writes external_dependencies.nix next to itself. It also prints the
# hashes for wazuh-http-request and modern.bpf.c, which pkgs/wazuh-agent.nix
# pins separately.
#
# Nix is optional. With nix-prefetch-url present the script uses it. Without it
# the script falls back to curl, sha256sum, and base64.

set -euo pipefail

# Find the value for a Wazuh tag at src/Makefile, variable DEPS_VERSION.
#   https://github.com/wazuh/wazuh/blob/v4.14.7/src/Makefile
DEPS_VERSION="${DEPS_VERSION:-54}"

# Wazuh tag the derivation builds. Used for the two extra hashes at the end.
WAZUH_VERSION="${WAZUH_VERSION:-4.14.7}"

# Commit that src/Makefile pins at HTTP_REQUEST_BRANCH for the tag above.
HTTP_REQUEST_REV="${HTTP_REQUEST_REV:-cd50797cfe03c27f3759bdc243fecca6f7535d35}"

# Override BASE_URL to fetch from a mirror.
BASE_URL="${BASE_URL:-https://packages.wazuh.com/deps/${DEPS_VERSION}/libraries/sources}"

# The Linux TARGET=agent dependency set. Manager-only names are excluded.
# Add manager-only names through EXTRA_DEPS if a build turns out to need them.
# Do not add cpython here. Its archive uses a per-architecture name and a
# different URL shape.
EXTERNAL_DEPS=(
	audit-userspace
	benchmark
	bzip2
	cJSON
	cpp-httplib
	curl
	dbus
	googletest
	libarchive
	libbpf-bootstrap
	libdb
	libffi
	libpcre2
	libplist
	libyaml
	lua
	lzma
	msgpack
	nlohmann
	openssl
	pacman
	popt
	procps
	rocksdb
	rpm
	sqlite
	zlib
)

read -r -a extra <<<"${EXTRA_DEPS:-}"
if [ "${#extra[@]}" -gt 0 ]; then
	EXTERNAL_DEPS+=("${extra[@]}")
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out_file="${script_dir}/external_dependencies.nix"
work_dir="$(mktemp -d)"
trap 'rm -rf "${work_dir}"' EXIT

# Convert a hex digest to a Subresource Integrity string.
hex_to_sri() {
	local hex="$1"
	printf 'sha256-%s' "$(printf '%b' "$(printf '%s' "${hex}" | sed 's/../\\x&/g')" | base64 -w0)"
}

# Print the SRI hash of a URL. Fails if the download is not a gzip archive.
sri_of_url() {
	local url="$1"
	local file="${work_dir}/download"

	local code
	code="$(curl -sS -L -o "${file}" -w '%{http_code}' "${url}")"
	if [ "${code}" != "200" ]; then
		echo "  HTTP ${code} for ${url}" >&2
		return 1
	fi
	if [ ! -s "${file}" ]; then
		echo "  empty body for ${url}" >&2
		return 1
	fi
	# Reject an HTML error page served with status 200.
	if [ "$(od -An -tx1 -N2 "${file}" | tr -d ' ')" != "1f8b" ]; then
		echo "  not a gzip archive: ${url}" >&2
		return 1
	fi

	hex_to_sri "$(sha256sum "${file}" | cut -d' ' -f1)"
}

# Print the SRI hash of a URL, preferring nix-prefetch-url when it is present.
sri_of() {
	local url="$1"
	if command -v nix-prefetch-url >/dev/null 2>&1 && command -v nix >/dev/null 2>&1; then
		nix-prefetch-url --type sha256 "${url}" 2>/dev/null |
			xargs nix hash convert --from nix32 --to sri --hash-algo sha256
	else
		sri_of_url "${url}"
	fi
}

echo "DEPS_VERSION ${DEPS_VERSION}, ${#EXTERNAL_DEPS[@]} dependencies, base ${BASE_URL}" >&2

tmp_out="${work_dir}/external_dependencies.nix"
failed=()

{
	echo "# Generated by prefetch-external-dependencies.sh."
	echo "# Wazuh DEPS_VERSION ${DEPS_VERSION}. Do not edit by hand."
	echo "{"
} >"${tmp_out}"

for dep in "${EXTERNAL_DEPS[@]}"; do
	printf '  %-20s ' "${dep}" >&2
	if hash_value="$(sri_of "${BASE_URL}/${dep}.tar.gz")" && [ -n "${hash_value}" ]; then
		echo "${hash_value}" >&2
		cat >>"${tmp_out}" <<EOF

  "${dep}" = {
    name = "${dep}";
    sha256 = "${hash_value}";
  };
EOF
	else
		echo "FAILED" >&2
		failed+=("${dep}")
	fi
done

echo "}" >>"${tmp_out}"

if [ "${#failed[@]}" -gt 0 ]; then
	echo >&2
	echo "FAILED: ${failed[*]}" >&2
	echo "${out_file} was not written. Fix the failures and run the script again." >&2
	exit 1
fi

mv "${tmp_out}" "${out_file}"
command -v alejandra >/dev/null 2>&1 && alejandra --quiet "${out_file}"
echo >&2
echo "Wrote ${out_file}" >&2

# Two hashes that pkgs/wazuh-agent.nix pins outside this file.
echo >&2
echo "Also update pkgs/wazuh-agent.nix with:" >&2

# fetchFromGitHub hashes cover the unpacked tree, so --unpack is required.
prefetch_github() {
	nix-prefetch-url --unpack --type sha256 "$1" 2>/dev/null |
		xargs nix hash convert --from nix32 --to sri --hash-algo sha256
}

echo "  wazuh-http-request rev    ${HTTP_REQUEST_REV}" >&2
if command -v nix-prefetch-url >/dev/null 2>&1 && command -v nix >/dev/null 2>&1; then
	echo "  wazuh src sha256          $(prefetch_github "https://github.com/wazuh/wazuh/archive/v${WAZUH_VERSION}.tar.gz")" >&2
	echo "  wazuh-http-request sha256 $(prefetch_github "https://github.com/wazuh/wazuh-http-request/archive/${HTTP_REQUEST_REV}.tar.gz")" >&2
else
	echo "  wazuh src sha256          needs nix-prefetch-url --unpack" >&2
	echo "  wazuh-http-request sha256 needs nix-prefetch-url --unpack" >&2
fi

bpf_url="https://raw.githubusercontent.com/wazuh/wazuh/v${WAZUH_VERSION}/src/syscheckd/src/ebpf/src/modern.bpf.c"
bpf_file="${work_dir}/modern.bpf.c"
if curl -sS -L -f -o "${bpf_file}" "${bpf_url}"; then
	echo "  modern.bpf.c hash         $(hex_to_sri "$(sha256sum "${bpf_file}" | cut -d' ' -f1)")" >&2
else
	echo "  modern.bpf.c hash         download failed: ${bpf_url}" >&2
fi
